# Copyright 2018- Rahul De
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.

FROM docker.io/bellsoft/liberica-openjdk-alpine-musl:23

COPY apiserver.jar .

ENTRYPOINT ["java", "--enable-preview", "-jar", "apiserver.jar"]
