# Copyright 2018- Rahul De
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.

FROM azul/zulu-openjdk:20 AS jdk

RUN apt-get update && apt-get install -y binutils

# should be --strip-java-debug-attributes on alpine
RUN jlink \
    --compress=2 \
    --module-path jmods \
    --add-modules java.base,java.sql,jdk.unsupported,java.naming,java.desktop,java.management,java.net.http \
    --strip-debug \
    --no-man-pages \
    --no-header-files \
    --output jlinked

# Optional TODO: check if unprivileged https://github.com/mgoltzsche/podman-static works
FROM quay.io/podman/stable:v4.4.2

COPY --from=jdk /jlinked jdk
COPY runner.jar .
RUN echo -e "set -e \n\
podman system service -t 0 unix:///tmp/pod.sock & \n\
/jdk/bin/java --enable-preview -jar runner.jar" > entrypoint.sh
ENV CONTAINER_ENGINE_URL "unix:///tmp/pod.sock"

ENTRYPOINT ["sh", "entrypoint.sh"]
